"""milestone 3 day3 - add indexes for leaderboard and lesson search performance

Revision ID: 18dfa19bf8d2
Revises: 2d3286b83cc9
Create Date: 2026-08-01 10:30:47.641232

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18dfa19bf8d2'
down_revision: Union[str, Sequence[str], None] = '2d3286b83cc9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_learning_analytics_average_accuracy'), 'learning_analytics', ['average_accuracy'], unique=False)
    op.create_index(op.f('ix_lessons_category'), 'lessons', ['category'], unique=False)
    op.create_index(op.f('ix_streaks_current_streak'), 'streaks', ['current_streak'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_streaks_current_streak'), table_name='streaks')
    op.drop_index(op.f('ix_lessons_category'), table_name='lessons')
    op.drop_index(op.f('ix_learning_analytics_average_accuracy'), table_name='learning_analytics')
    # ### end Alembic commands ###
