"""milestone 4 day2 - add certification_exams and trainer_learners tables

Revision ID: 3cf2fd380d75
Revises: 18dfa19bf8d2
Create Date: 2026-08-14 11:27:07.516987

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3cf2fd380d75'
down_revision: Union[str, Sequence[str], None] = '18dfa19bf8d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trainer_learners',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trainer_id', sa.Integer(), nullable=False),
    sa.Column('learner_id', sa.Integer(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['learner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['trainer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('learner_id')
    )
    op.create_index(op.f('ix_trainer_learners_id'), 'trainer_learners', ['id'], unique=False)
    op.create_index(op.f('ix_trainer_learners_trainer_id'), 'trainer_learners', ['trainer_id'], unique=False)
    op.create_table('certification_exams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('learner_id', sa.Integer(), nullable=False),
    sa.Column('level', sa.String(length=30), nullable=False),
    sa.Column('signs_tested', sa.Text(), nullable=False),
    sa.Column('overall_score', sa.Float(), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=True),
    sa.Column('certificate_id', sa.Integer(), nullable=True),
    sa.Column('taken_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['certificate_id'], ['certificates.id'], ),
    sa.ForeignKeyConstraint(['learner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_certification_exams_id'), 'certification_exams', ['id'], unique=False)
    op.create_index(op.f('ix_certification_exams_learner_id'), 'certification_exams', ['learner_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_certification_exams_learner_id'), table_name='certification_exams')
    op.drop_index(op.f('ix_certification_exams_id'), table_name='certification_exams')
    op.drop_table('certification_exams')
    op.drop_index(op.f('ix_trainer_learners_trainer_id'), table_name='trainer_learners')
    op.drop_index(op.f('ix_trainer_learners_id'), table_name='trainer_learners')
    op.drop_table('trainer_learners')
    # ### end Alembic commands ###
