"""milestone 2 - add recommendations, instructor_students, weekly_analytics tables, lesson category/difficulty, assessment possible_issue, certificate pdf_path

Revision ID: e24d36ae8fdd
Revises: 6e013ae949f2
Create Date: 2026-07-14 11:26:49.102734

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e24d36ae8fdd'
down_revision: Union[str, Sequence[str], None] = '6e013ae949f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('instructor_students',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instructor_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['instructor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id')
    )
    op.create_index(op.f('ix_instructor_students_id'), 'instructor_students', ['id'], unique=False)
    op.create_table('recommendations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('learner_id', sa.Integer(), nullable=False),
    sa.Column('sign', sa.String(length=50), nullable=False),
    sa.Column('recommended_sessions', sa.Integer(), nullable=True),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['learner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recommendations_id'), 'recommendations', ['id'], unique=False)
    op.create_table('weekly_analytics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('learner_id', sa.Integer(), nullable=False),
    sa.Column('week_start_date', sa.DateTime(), nullable=False),
    sa.Column('sessions_this_week', sa.Integer(), nullable=True),
    sa.Column('average_accuracy_this_week', sa.Float(), nullable=True),
    sa.Column('improvement_rate', sa.Float(), nullable=True),
    sa.Column('weak_signs_this_week', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['learner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_weekly_analytics_id'), 'weekly_analytics', ['id'], unique=False)
    op.add_column('assessments', sa.Column('possible_issue', sa.String(length=255), nullable=True))
    op.add_column('certificates', sa.Column('pdf_path', sa.String(length=500), nullable=True))
    op.add_column('lessons', sa.Column('category', sa.String(length=30), nullable=True))
    op.add_column('lessons', sa.Column('difficulty', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lessons', 'difficulty')
    op.drop_column('lessons', 'category')
    op.drop_column('certificates', 'pdf_path')
    op.drop_column('assessments', 'possible_issue')
    op.drop_index(op.f('ix_weekly_analytics_id'), table_name='weekly_analytics')
    op.drop_table('weekly_analytics')
    op.drop_index(op.f('ix_recommendations_id'), table_name='recommendations')
    op.drop_table('recommendations')
    op.drop_index(op.f('ix_instructor_students_id'), table_name='instructor_students')
    op.drop_table('instructor_students')
    # ### end Alembic commands ###
